/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InterfaceGraphique;

import ClassesVehicule.HoraireTrain;
import Thread.ThreadApplicDepot;
import java.awt.BorderLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import network.NetworkStringSender;
import serialize.ObjectLoader;

/**
 *
 * @author Julien
 */

@SuppressWarnings({"FieldMayBeFinal", "OverridableMethodCallInConstructor"})
public class FenApplicDepot extends javax.swing.JFrame
{
    private NetworkStringSender NSS;
    private Vector<HoraireTrain> vctHoraireTrain;
    private Properties PropertyFile;
    private String sep;
    private String repHome;
    private String cheminFichier;
    

    /**
     * Creates new form FenApplicDepot
     */

    public FenApplicDepot()
    {
        initComponents();
        setTitle("Applic_Depôt");
        
        sep = System.getProperty("file.separator");
        repHome = System.getProperty("user.home");
        cheminFichier = repHome + sep + "Documents" + sep + "NetBeansProjects" + sep;
        
        JLabel image = new JLabel(new ImageIcon(cheminFichier + "Applic_Depot" + sep + "FrontImage.png"));
        panelImage.setLayout(new BorderLayout());
        panelImage.add(image,BorderLayout.CENTER);
        
        LoadPropertiesFile(); // Chargement du fichier ApplicDepotProperties.properties
        
        tfTrainConsidere.setEditable(false);
        tfTrainConsidere.setText(null);
        tfAnnonce.setEditable(false);
        tfAnnonce.setText(null);
        
        ThreadApplicDepot TAD = new ThreadApplicDepot(tfAnnonce, tfTrainConsidere, tableOccupationVoie, cbVoieChoisie, Integer.valueOf((String)PropertyFile.get("PortNSR")));
        TAD.start();
        
        btSignalerArriveeTrain.setEnabled(false);
            
        vctHoraireTrain = new Vector<>();
        LoadHoraireTrain(); // Chargement du fichier HoraireTrainLiege.dat dans un vecteur
    }
    
    public void LoadHoraireTrain()
    {
        File f = new File(cheminFichier + "Applic_Gare" + sep + "HoraireTrainLiege.dat");
        
        try
        {
            if (f.exists()) // Le fichier existe -> On charge les données
            {
                ObjectLoader OL = new ObjectLoader(cheminFichier + "Applic_Gare" + sep + "HoraireTrainLiege.dat");
                vctHoraireTrain = (Vector<HoraireTrain>)OL.load();
            }
            else
                System.out.println("Fichier inexistant");
        }
        catch (IOException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            Logger.getLogger(FenApplicDepot.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            Logger.getLogger(FenApplicDepot.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void LoadPropertiesFile()
    {
        PropertyFile = new Properties();
        try
        {
            FileInputStream FIS = new FileInputStream(cheminFichier + "Applic_Depot" + sep + "ressources" + sep + "ApplicDepotProperties.properties");
            try
            {
                PropertyFile.load(FIS);
            }
            catch (IOException ex)
            {
                Logger.getLogger(FenApplicDepot.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        catch (FileNotFoundException ex)
        {
            Logger.getLogger(FenApplicDepot.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTrainConsidere = new javax.swing.JLabel();
        tfTrainConsidere = new javax.swing.JTextField();
        panelImage = new javax.swing.JPanel();
        btMessageRecu = new javax.swing.JButton();
        lbAnnonce = new javax.swing.JLabel();
        tfAnnonce = new javax.swing.JTextField();
        btSignalerArriveeTrain = new javax.swing.JButton();
        lbVoieChoisie = new javax.swing.JLabel();
        cbVoieChoisie = new javax.swing.JComboBox();
        btValiderVoie = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOccupationVoie = new javax.swing.JTable();
        lbOccupationHanger = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTrainConsidere.setText("Train considéré: ");

        tfTrainConsidere.setText("Default");

        javax.swing.GroupLayout panelImageLayout = new javax.swing.GroupLayout(panelImage);
        panelImage.setLayout(panelImageLayout);
        panelImageLayout.setHorizontalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImageLayout.setVerticalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btMessageRecu.setText("Message reçu");
        btMessageRecu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMessageRecuActionPerformed(evt);
            }
        });

        lbAnnonce.setText("Annonce: ");

        tfAnnonce.setText("Default");

        btSignalerArriveeTrain.setText("Signaler arrivée du train");
        btSignalerArriveeTrain.setEnabled(false);
        btSignalerArriveeTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignalerArriveeTrainActionPerformed(evt);
            }
        });

        lbVoieChoisie.setText("Voie choisie: ");

        cbVoieChoisie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        btValiderVoie.setText("Valider");
        btValiderVoie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderVoieActionPerformed(evt);
            }
        });

        tableOccupationVoie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Voie", "Train N°", "Arrivée", "Nombre wagons"
            }
        ));
        jScrollPane1.setViewportView(tableOccupationVoie);

        lbOccupationHanger.setText("Occupation du hanger: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbOccupationHanger)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbTrainConsidere)
                                            .addComponent(btMessageRecu)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(tfTrainConsidere, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lbAnnonce)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfAnnonce))
                                            .addComponent(btSignalerArriveeTrain))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbVoieChoisie)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbVoieChoisie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btValiderVoie)
                                    .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTrainConsidere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTrainConsidere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMessageRecu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAnnonce)
                            .addComponent(tfAnnonce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btValiderVoie)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSignalerArriveeTrain)
                        .addComponent(lbVoieChoisie)
                        .addComponent(cbVoieChoisie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lbOccupationHanger)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMessageRecuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMessageRecuActionPerformed
        if (NSS == null)
            NSS = new NetworkStringSender((String)PropertyFile.get("AdresseReseau"), Integer.valueOf((String)PropertyFile.get("PortNSS")));
        
        NSS.sendString("ACK");
        tfAnnonce.setText(null);
        btMessageRecu.setEnabled(false);
        btSignalerArriveeTrain.setEnabled(true);
    }//GEN-LAST:event_btMessageRecuActionPerformed

    private void btSignalerArriveeTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignalerArriveeTrainActionPerformed
        if (NSS == null)
            NSS = new NetworkStringSender((String)PropertyFile.get("AdresseReseau"), Integer.valueOf((String)PropertyFile.get("PortNSS")));
        
        NSS.sendString("Train passé!");
        btSignalerArriveeTrain.setEnabled(false);
    }//GEN-LAST:event_btSignalerArriveeTrainActionPerformed

    private void btValiderVoieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderVoieActionPerformed
        for (int i = 0; i < vctHoraireTrain.size(); i++)
        {
            System.out.println(vctHoraireTrain.get(i).getTrain().getIdentifiant()+ " - " + tfTrainConsidere.getText().substring(0, 7));
            
            if (vctHoraireTrain.get(i).getTrain().getIdentifiant().equals(tfTrainConsidere.getText().substring(0, 7)))
            {
                DefaultTableModel md = (DefaultTableModel)tableOccupationVoie.getModel();
                md.setValueAt(vctHoraireTrain.get(i).getTrain().getIdentifiant(), cbVoieChoisie.getSelectedIndex(), 1);
                md.setValueAt(vctHoraireTrain.get(i).getHeureArrivee(), cbVoieChoisie.getSelectedIndex(), 2);
                md.setValueAt(vctHoraireTrain.get(i).getTrain().getVecWagon().size(), cbVoieChoisie.getSelectedIndex(), 3);
                
                break;
            }
        }
        cbVoieChoisie.removeItemAt(cbVoieChoisie.getSelectedIndex());
        tfTrainConsidere.setText(null);
        btMessageRecu.setEnabled(true);
    }//GEN-LAST:event_btValiderVoieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenApplicDepot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenApplicDepot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenApplicDepot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenApplicDepot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenApplicDepot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMessageRecu;
    private javax.swing.JButton btSignalerArriveeTrain;
    private javax.swing.JButton btValiderVoie;
    private javax.swing.JComboBox cbVoieChoisie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAnnonce;
    private javax.swing.JLabel lbOccupationHanger;
    private javax.swing.JLabel lbTrainConsidere;
    private javax.swing.JLabel lbVoieChoisie;
    private javax.swing.JPanel panelImage;
    private javax.swing.JTable tableOccupationVoie;
    private javax.swing.JTextField tfAnnonce;
    private javax.swing.JTextField tfTrainConsidere;
    // End of variables declaration//GEN-END:variables
}
