/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InterfaceGraphique;

import Thread.ThreadApplicPoste;
import java.awt.BorderLayout;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayDeque;
import java.util.Enumeration;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import network.NetworkStringSender;

/**
 *
 * @author Julien
 */
@SuppressWarnings({"FieldMayBeFinal"})
public class FenApplicPoste extends javax.swing.JFrame 
{
    private ThreadApplicPoste TAP;
    private NetworkStringSender NSS;
    private Vector<String> vctTrainsPartis;
    private Properties PropertyFile;
    private String sep;
    private String cheminFichier;

    /**
     * Creates new form FenApplicPoste
     */
    
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public FenApplicPoste()
    {
        initComponents();
        setTitle("Applic_Postes");
        
        sep = System.getProperty("file.separator");
        cheminFichier = System.getProperty("user.home") + sep + "Documents" + sep + "NetBeansProjects" + sep;
         
        /***** Chargement de l'image *****/
        
        JLabel image = new JLabel(new ImageIcon(cheminFichier + "Applic_Poste" + sep + "FrontImage.png"));
        panelImage.setLayout(new BorderLayout());
        panelImage.add(image,BorderLayout.CENTER);
        
        btSignalerPassageTrain.setEnabled(false);
        tfAnnonce.setEditable(false);
        tfAnnonce.setText(null);
        tfTrainConsidere.setEditable(false);
        tfTrainConsidere.setText(null);
        vctTrainsPartis = new Vector<>();
        
        LoadPropertiesFile(); // Chargement du fichier ApplicPosteProperties.properties
    }
    
    public void LoadPropertiesFile()
    {
        PropertyFile = new Properties();
        
        try
        {
            FileInputStream FIS = new FileInputStream(cheminFichier + "Applic_Poste" + sep + "ressources" + sep + "ApplicPosteProperties.properties");
            try
            {
                PropertyFile.load(FIS);
            }
            catch (IOException ex)
            {
                Logger.getLogger(FenApplicPoste.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        catch (FileNotFoundException ex)
        {
            Logger.getLogger(FenApplicPoste.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbChoixPoste = new javax.swing.JComboBox();
        btValider = new javax.swing.JButton();
        lbAnnonce = new javax.swing.JLabel();
        tfAnnonce = new javax.swing.JTextField();
        btMessageRecu = new javax.swing.JButton();
        lbTrainConsidere = new javax.swing.JLabel();
        tfTrainConsidere = new javax.swing.JTextField();
        btSignalerPassageTrain = new javax.swing.JButton();
        lbTrainsPartis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lTrainsPartis = new javax.swing.JList();
        panelImage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbChoixPoste.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Poste de contrôle in", "Poste de contrôle out" }));

        btValider.setText("Valider");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });

        lbAnnonce.setText("Annonce: ");

        tfAnnonce.setText("Default");

        btMessageRecu.setText("Message reçu");
        btMessageRecu.setEnabled(false);
        btMessageRecu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMessageRecuActionPerformed(evt);
            }
        });

        lbTrainConsidere.setText("Train considéré: ");

        tfTrainConsidere.setText("Default");

        btSignalerPassageTrain.setText("Signaler passage train");
        btSignalerPassageTrain.setEnabled(false);
        btSignalerPassageTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignalerPassageTrainActionPerformed(evt);
            }
        });

        lbTrainsPartis.setText("Trains partis: ");

        jScrollPane1.setViewportView(lTrainsPartis);

        javax.swing.GroupLayout panelImageLayout = new javax.swing.GroupLayout(panelImage);
        panelImage.setLayout(panelImageLayout);
        panelImageLayout.setHorizontalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImageLayout.setVerticalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSignalerPassageTrain)
                        .addGap(18, 18, 18)
                        .addComponent(lbTrainsPartis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTrainConsidere)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfTrainConsidere, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbAnnonce)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfAnnonce))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btMessageRecu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbChoixPoste, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btValider)))
                                .addGap(18, 18, 18)
                                .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbChoixPoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btValider))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAnnonce)
                            .addComponent(tfAnnonce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btMessageRecu))
                    .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTrainConsidere)
                    .addComponent(tfTrainConsidere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSignalerPassageTrain)
                        .addComponent(lbTrainsPartis))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        cbChoixPoste.setEnabled(false);
        
        TAP = new ThreadApplicPoste(tfAnnonce, tfTrainConsidere);
        
        if (cbChoixPoste.getSelectedIndex() == 0)
        {
            TAP.setControleIn(true);
            TAP.setPort(Integer.valueOf((String)PropertyFile.get("PortNSRIN")));
        }
        else
        {
            TAP.setControleIn(false);
            TAP.setPort(Integer.valueOf((String)PropertyFile.get("PortNSROUT")));
        }
        
        TAP.start();
        btValider.setEnabled(false);
        btMessageRecu.setEnabled(true);
    }//GEN-LAST:event_btValiderActionPerformed

    private void btMessageRecuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMessageRecuActionPerformed
        if (NSS == null)
        {
            if (cbChoixPoste.getSelectedIndex() == 0)
                NSS = new NetworkStringSender((String)PropertyFile.get("AdresseReseau"), Integer.valueOf((String)PropertyFile.get("PortNSSIN")));
            else
                NSS = new NetworkStringSender((String)PropertyFile.get("AdresseReseau"), Integer.valueOf((String)PropertyFile.get("PortNSSOUT")));
        }
        
        NSS.sendString("ACK");
        
        tfAnnonce.setText(null);
        btSignalerPassageTrain.setEnabled(true);
        btMessageRecu.setEnabled(false);
    }//GEN-LAST:event_btMessageRecuActionPerformed

    private void btSignalerPassageTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignalerPassageTrainActionPerformed
        NSS.sendString("Train passé!");
        
        vctTrainsPartis.addElement(tfTrainConsidere.getText());
        lTrainsPartis.removeAll();
        
        DefaultListModel dlm = new DefaultListModel();
        
        Enumeration e = vctTrainsPartis.elements();
        
        while (e.hasMoreElements())
            dlm.addElement(e.nextElement());
        
        lTrainsPartis.setModel(dlm);
        
        tfTrainConsidere.setText(null);
        btMessageRecu.setEnabled(true);
        btSignalerPassageTrain.setEnabled(false);
    }//GEN-LAST:event_btSignalerPassageTrainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenApplicPoste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenApplicPoste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenApplicPoste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenApplicPoste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenApplicPoste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMessageRecu;
    private javax.swing.JButton btSignalerPassageTrain;
    private javax.swing.JButton btValider;
    private javax.swing.JComboBox cbChoixPoste;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lTrainsPartis;
    private javax.swing.JLabel lbAnnonce;
    private javax.swing.JLabel lbTrainConsidere;
    private javax.swing.JLabel lbTrainsPartis;
    private javax.swing.JPanel panelImage;
    private javax.swing.JTextField tfAnnonce;
    private javax.swing.JTextField tfTrainConsidere;
    // End of variables declaration//GEN-END:variables
}
