/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FenAjoutUser.java
 *
 * Created on 18-avr.-2014, 1:32:50
 */
package InterfaceGraphique;

import Authenticate.User;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import serialize.ObjectLoader;
import serialize.ObjectSaver;

/**
 *
 * @author Julien
 */

@SuppressWarnings("FieldMayBeFinal")
public class FenAjoutUser extends javax.swing.JDialog
{
    private static HashMap HM;
    private String sep;
    private String cheminFichier;
    /** Creates new form FenAjoutUser */
    public FenAjoutUser(java.awt.Frame parent, boolean modal, HashMap HMUsers)
    {
        super(parent, modal);
        initComponents();
        this.setTitle("Ajouter un utilisateur");
        cbRole.removeAllItems();
        cbRole.addItem("Administrateur");
        cbRole.addItem("Chef de gare");
        
        sep = System.getProperty("file.separator");
        cheminFichier = System.getProperty("user.home") + sep + "Documents" + sep + "NetBeansProjects" + sep + "Applic_Gare" + sep;
        
        HM = HMUsers;
        LoadHashMap();        
    }
    
    private void LoadHashMap()
    {
        File f = new File(cheminFichier + "Users.dat");
        
        if(f.exists())
        {
            ObjectLoader OL = new ObjectLoader(cheminFichier + "Users.dat");
            try 
            {
                HM = (HashMap)OL.load();
            } 
            catch (IOException ex)
            {
                Logger.getLogger(FenAjoutUser.class.getName()).log(Level.SEVERE, null, ex);
            } 
            catch (ClassNotFoundException ex) 
            {
                Logger.getLogger(FenAjoutUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLogin = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbRole = new javax.swing.JLabel();
        btAjout = new javax.swing.JButton();
        tfLogin = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        cbRole = new javax.swing.JComboBox();
        lbErreur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbLogin.setText("Login: ");

        lbPassword.setText("Mot de passe: ");

        lbRole.setText("Role: ");

        btAjout.setText("Ajouter");
        btAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjoutActionPerformed(evt);
            }
        });

        cbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbErreur.setFont(new java.awt.Font("Tahoma", 0, 18));
        lbErreur.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbErreur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addComponent(btAjout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbRole)
                        .addGap(100, 100, 100)
                        .addComponent(cbRole, 0, 291, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPassword)
                        .addGap(57, 57, 57)
                        .addComponent(tfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(tfLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbErreur, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogin)
                    .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPassword)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRole))
                .addGap(18, 18, 18)
                .addComponent(btAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjoutActionPerformed
        if (tfLogin.getText().isEmpty())
            lbErreur.setText("Le champ login est vide ...");
        else if (tfPassword.getText().isEmpty())
            lbErreur.setText("Le champ mot de passe est vide ...");
        else
        {
            lbErreur.setText("");
            String role = null;
            switch(cbRole.getSelectedIndex())
            {
                case 0: role = "Admin";
                    break;

                case 1: role = "Chef";
                    break;
            }
            
            User userAdd = new User(tfLogin.getText(), tfPassword.getText(), role);
            HM.put(tfLogin.getText(), userAdd);
            
            ObjectSaver OS = new ObjectSaver(cheminFichier + "Users.dat");
            try 
            {
                OS.save(HM);
            } 
            catch (IOException ex)
            {
                Logger.getLogger(FenAjoutUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
    }//GEN-LAST:event_btAjoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FenAjoutUser dialog = new FenAjoutUser(new javax.swing.JFrame(), true, HM);
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) 
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjout;
    private javax.swing.JComboBox cbRole;
    private javax.swing.JLabel lbErreur;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbRole;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfPassword;
    // End of variables declaration//GEN-END:variables
}
