/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InterfaceGraphique;

import ClassesVehicule.HoraireTrain;
import ClassesVehicule.Train;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julien
 */
public class FenFormationTrain extends javax.swing.JDialog 
{
    private HoraireTrain NewHoraireTrain;
    private Vector<Train> vecTrainDepot;
    private boolean Valide;

    /**
     * Creates new form FenFormationTrain
     */
    public FenFormationTrain(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }
    
    public FenFormationTrain(java.awt.Frame parent, boolean modal, Vector<Train> vctTrain) 
    {
        super(parent, modal);        
        initComponents();
        DefaultTableModel md = (DefaultTableModel)tableTrains.getModel();
        
        setTitle("Formation de trains");
        
        vecTrainDepot = vctTrain;
        
        for (int i = 0; i < vecTrainDepot.size(); i++)
        {
            md.addRow(new Object[]
            {vecTrainDepot.get(i).toString()});
        }
        
        tfLieuArrivee.setText(null);
        tfLieuDepart.setText(null);
        
        cbArriveeHeure.removeAllItems();
        cbArriveeMinutes.removeAllItems();
        cbDepartHeure.removeAllItems();
        cbDepartMinutes.removeAllItems();
        
        for (int i = 0; i < 60; i++)
        {
            if (i < 10)
            {
                cbArriveeHeure.addItem("0" + i);
                cbArriveeMinutes.addItem("0" + i);
                cbDepartHeure.addItem("0" + i);
                cbDepartMinutes.addItem("0" + i);
            }
            else
            {
                if (i < 24)
                {
                    cbArriveeHeure.addItem(i);
                    cbDepartHeure.addItem(i);
                }
                
                cbArriveeMinutes.addItem(i);
                cbDepartMinutes.addItem(i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTrains = new javax.swing.JTable();
        lbDonnees = new javax.swing.JLabel();
        lbHeureArrivee = new javax.swing.JLabel();
        lbHeureDepart = new javax.swing.JLabel();
        lbType = new javax.swing.JLabel();
        lbLieuDepart = new javax.swing.JLabel();
        lbLieuArrivee = new javax.swing.JLabel();
        lbQuai = new javax.swing.JLabel();
        cbArriveeHeure = new javax.swing.JComboBox();
        cbArriveeMinutes = new javax.swing.JComboBox();
        cbDepartHeure = new javax.swing.JComboBox();
        cbDepartMinutes = new javax.swing.JComboBox();
        cbType = new javax.swing.JComboBox();
        tfLieuDepart = new javax.swing.JTextField();
        tfLieuArrivee = new javax.swing.JTextField();
        cbQuai = new javax.swing.JComboBox();
        btAnnuler = new javax.swing.JButton();
        btValider = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableTrains.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trains"
            }
        ));
        jScrollPane1.setViewportView(tableTrains);

        lbDonnees.setText("Données du train:");

        lbHeureArrivee.setText("Heure d'arrivées: ");

        lbHeureDepart.setText("Heure de départ: ");

        lbType.setText("Type: ");

        lbLieuDepart.setText("Lieu de départ: ");

        lbLieuArrivee.setText("Lieu d'arrivée: ");

        lbQuai.setText("Quai: ");

        cbArriveeHeure.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbArriveeMinutes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDepartHeure.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDepartMinutes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Voyageurs", "Marchandises" }));

        tfLieuDepart.setText("jTextField2");

        tfLieuArrivee.setText("jTextField1");

        cbQuai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        btAnnuler.setText("Annuler la formation de train");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });

        btValider.setText("Valider la formation de train");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbHeureArrivee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbArriveeHeure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbArriveeMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHeureDepart)
                                    .addComponent(lbType))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbDepartHeure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbDepartMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLieuArrivee)
                            .addComponent(lbQuai)
                            .addComponent(lbLieuDepart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLieuDepart)
                            .addComponent(tfLieuArrivee)
                            .addComponent(cbQuai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDonnees)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(btValider, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDonnees)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbArriveeHeure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbArriveeMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLieuDepart)
                        .addComponent(tfLieuDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbHeureArrivee))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHeureDepart)
                    .addComponent(cbDepartHeure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDepartMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLieuArrivee)
                    .addComponent(tfLieuArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbType)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuai)
                    .addComponent(cbQuai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAnnuler)
                    .addComponent(btValider))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        if (!tfLieuArrivee.getText().equals("") && !tfLieuDepart.getText().equals("") && tableTrains.getSelectedRow() >= 0)
        {
            System.out.println("Ajout : done");

            int rowIndex = tableTrains.getSelectedRow();
            Train TrainUtilise = vecTrainDepot.get(rowIndex);

            String HeureArrivee = cbArriveeHeure.getSelectedItem().toString() + ":" + cbArriveeMinutes.getSelectedItem().toString();
            String HeureDepart = cbDepartHeure.getSelectedItem().toString() + ":" + cbDepartMinutes.getSelectedItem().toString();
            NewHoraireTrain = new HoraireTrain(TrainUtilise, HeureArrivee, HeureDepart, cbType.getSelectedItem().toString(), tfLieuDepart.getText(), tfLieuArrivee.getText(), Integer.parseInt(cbQuai.getSelectedItem().toString()));
            
            setValide(true);
            
            this.dispose();
        }
        else
            System.out.println(" ! Champs incomplet ! ");
    }//GEN-LAST:event_btValiderActionPerformed

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenFormationTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenFormationTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenFormationTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenFormationTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FenFormationTrain dialog = new FenFormationTrain(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btValider;
    private javax.swing.JComboBox cbArriveeHeure;
    private javax.swing.JComboBox cbArriveeMinutes;
    private javax.swing.JComboBox cbDepartHeure;
    private javax.swing.JComboBox cbDepartMinutes;
    private javax.swing.JComboBox cbQuai;
    private javax.swing.JComboBox cbType;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDonnees;
    private javax.swing.JLabel lbHeureArrivee;
    private javax.swing.JLabel lbHeureDepart;
    private javax.swing.JLabel lbLieuArrivee;
    private javax.swing.JLabel lbLieuDepart;
    private javax.swing.JLabel lbQuai;
    private javax.swing.JLabel lbType;
    private javax.swing.JTable tableTrains;
    private javax.swing.JTextField tfLieuArrivee;
    private javax.swing.JTextField tfLieuDepart;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the NewHoraireTrain
     */
    public HoraireTrain getNewHoraireTrain() {
        return NewHoraireTrain;
    }

    /**
     * @return the vecTrainDepot
     */
    public Vector<Train> getVecTrainDepot() {
        return vecTrainDepot;
    }

    /**
     * @param NewHoraireTrain the NewHoraireTrain to set
     */
    public void setNewHoraireTrain(HoraireTrain NewHoraireTrain) {
        this.NewHoraireTrain = NewHoraireTrain;
    }

    /**
     * @param vecTrainDepot the vecTrainDepot to set
     */
    public void setVecTrainDepot(Vector<Train> vecTrainDepot) {
        this.vecTrainDepot = vecTrainDepot;
    }

    /**
     * @return the Valide
     */
    public boolean isValide() {
        return Valide;
    }

    /**
     * @param Valide the Valide to set
     */
    public void setValide(boolean Valide) {
        this.Valide = Valide;
    }
}
