/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InterfaceGraphique;

import Bean.EventEvent;
import Outils.FichierLog;
import javax.swing.JLabel;

/**
 *
 * @author Julien
 */
public class FenIncident extends javax.swing.JDialog
{
    private EventEvent EE;
    private FichierLog FL;
    
    /**
     * Creates new form FenIncident
     */
    public FenIncident(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        setTitle("Un incident s'est produit");
        EE = new EventEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNature = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        lbValHeure = new javax.swing.JLabel();
        lbValMinRetard = new javax.swing.JLabel();
        btResoudreIncident = new javax.swing.JButton();
        lbHeure = new javax.swing.JLabel();
        lbMinRetard = new javax.swing.JLabel();
        lbValDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNature.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lbNature.setText("Default");

        lbDate.setText("Date: ");

        lbValHeure.setText("Default");

        lbValMinRetard.setText("Default");

        btResoudreIncident.setText("Résoudre l'incident");
        btResoudreIncident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResoudreIncidentActionPerformed(evt);
            }
        });

        lbHeure.setText("Heure: ");

        lbMinRetard.setText("Minutes de retard: ");

        lbValDate.setText("Default");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNature, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDate)
                            .addComponent(lbHeure)
                            .addComponent(lbMinRetard))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbValDate)
                            .addComponent(lbValHeure)
                            .addComponent(lbValMinRetard))
                        .addGap(0, 205, Short.MAX_VALUE))
                    .addComponent(btResoudreIncident, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNature, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDate)
                    .addComponent(lbValDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHeure)
                    .addComponent(lbValHeure))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMinRetard)
                    .addComponent(lbValMinRetard))
                .addGap(18, 18, 18)
                .addComponent(btResoudreIncident)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btResoudreIncidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResoudreIncidentActionPerformed
        this.dispose();
    }//GEN-LAST:event_btResoudreIncidentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenIncident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenIncident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenIncident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenIncident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FenIncident dialog = new FenIncident(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btResoudreIncident;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbHeure;
    private javax.swing.JLabel lbMinRetard;
    private javax.swing.JLabel lbNature;
    private javax.swing.JLabel lbValDate;
    private javax.swing.JLabel lbValHeure;
    private javax.swing.JLabel lbValMinRetard;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the EE
     */
    public EventEvent getEE() {
        return EE;
    }

    /**
     * @return the FL
     */
    public FichierLog getFL() {
        return FL;
    }

    /**
     * @param EE the EE to set
     */
    public void setEE(EventEvent EE) {
        this.EE = EE;
        lbNature.setText(EE.getNature());
        lbNature.setHorizontalAlignment(JLabel.CENTER);
        lbValDate.setText(EE.getDate());
        lbValHeure.setText(EE.getHeure());
        if (EE.getNature().equals("RETARD"))
            lbValMinRetard.setText(EE.getMinRetard());
        else
        {
            lbValMinRetard.setVisible(false);
            lbMinRetard.setVisible(false);
        }
    }

    /**
     * @param FL the FL to set
     */
    public void setFL(FichierLog FL) {
        this.FL = FL;
        FL.ecritLigne("l'incident : "+ EE.getNature() + " est maintenant résolu!");
    }
}
