/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FenParametreDates.java
 *
 * Created on 16-avr.-2014, 17:32:04
 */
package InterfaceGraphique;

import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author Julien
 */
public class FenParametreDates extends javax.swing.JDialog {

    private String date;
    /** Creates new form FenParametreDates */
    public FenParametreDates(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.setTitle("Paramètre de date");
        cbPays.removeAllItems();
        cbPays.addItem("France");
        cbPays.addItem("Royaume-Uni");
        cbPays.addItem("Allemagne");
        cbPays.addItem("Italie");
        cbPays.addItem("USA");
        cbFormatDate.removeAllItems();
        cbFormatDate.addItem("JJ/MM/YYYY");
        cbFormatDate.addItem("JJ-Month-YYYY");
        cbFormatDate.addItem("DAY-DD MONTH YYYY");
        cbFormatHeure.removeAllItems();
        cbFormatHeure.addItem("HH:MM");
        cbFormatHeure.addItem("HH:MM:SS");
        cbFormatHeure.addItem("HH heure MM");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPays = new javax.swing.JComboBox();
        cbFormatDate = new javax.swing.JComboBox();
        cbFormatHeure = new javax.swing.JComboBox();
        lbPays = new javax.swing.JLabel();
        lbFormatDate = new javax.swing.JLabel();
        lbFormatHeure = new javax.swing.JLabel();
        btValider = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbPays.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbFormatDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbFormatHeure.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbPays.setText("Pays: ");

        lbFormatDate.setText("Format de la date: ");

        lbFormatHeure.setText("Format de l'heure: ");

        btValider.setText("Valider");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });

        btAnnuler.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFormatDate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPays)
                    .addComponent(lbFormatHeure)
                    .addComponent(btValider))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbFormatDate, javax.swing.GroupLayout.Alignment.LEADING, 0, 244, Short.MAX_VALUE)
                    .addComponent(cbPays, javax.swing.GroupLayout.Alignment.LEADING, 0, 244, Short.MAX_VALUE)
                    .addComponent(cbFormatHeure, javax.swing.GroupLayout.Alignment.LEADING, 0, 244, Short.MAX_VALUE)
                    .addComponent(btAnnuler))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPays)
                    .addComponent(cbPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFormatDate)
                    .addComponent(cbFormatDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFormatHeure)
                    .addComponent(cbFormatHeure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAnnuler)
                    .addComponent(btValider))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed

        Locale Pays = Locale.FRANCE;
        int DF = 0;
        int DFDate = 0;

        switch(cbPays.getSelectedIndex())
        {
            case 0:
                Pays = Locale.FRANCE;
                break;
            case 1:
                Pays = Locale.UK;
                break;
            case 2:
                Pays = Locale.GERMANY;
                break;
            case 3:
                Pays = Locale.ITALY;
                break;
            case 4:
                Pays = Locale.US;
                break;
        }

        switch (cbFormatDate.getSelectedIndex())
        {
            case 0:
                DFDate = DateFormat.SHORT;
                break;
            case 1:
                DFDate = DateFormat.MEDIUM;
                break;
            case 2:
                DFDate = DateFormat.FULL;
                break;
        }

        switch (cbFormatHeure.getSelectedIndex())
        {
            case 0:
                DF = DateFormat.SHORT;
                break;
            case 1:
                DF = DateFormat.MEDIUM;
                break;
            case 2:
                DF = DateFormat.FULL;
                break;
        }
        Date Now = new Date();
        setDate(DateFormat.getDateTimeInstance(DFDate,DF, Pays).format(Now));
        this.dispose();
    }//GEN-LAST:event_btValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FenParametreDates dialog = new FenParametreDates(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btValider;
    private javax.swing.JComboBox cbFormatDate;
    private javax.swing.JComboBox cbFormatHeure;
    private javax.swing.JComboBox cbPays;
    private javax.swing.JLabel lbFormatDate;
    private javax.swing.JLabel lbFormatHeure;
    private javax.swing.JLabel lbPays;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the date
     */
    public String getDate() {
        return date;
    }

    /**
     * @param date the date to set
     */
    public void setDate(String date) {
        this.date = date;
    }
}
